# Generated by Django 3.2.9 on 2021-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('razon_social', models.CharField(max_length=120)),
                ('NIT', models.CharField(max_length=10)),
                ('num_empleados', models.IntegerField()),
                ('logo', models.CharField(max_length=120)),
            ],
        ),
    ]
