# Generated by Django 3.2.9 on 2021-12-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_auto_20211130_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=512)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa')),
            ],
        ),
    ]
